### ISSUE TITLE
Emotion 추가

### ISSUE THREAD

**Issue by KimDoubleB** [Team-Archive/ArchiveServer#5]
## TO-BE

- 신선한 (`FRESH`)
- 흥미로운 (`INTERESTING2`)
- 감동적인 (`TOUCHING`)

**Comment by HanweeeeLee** [comment]
👏 INTERESTING2로 되었군요..!

**Comment by KimDoubleB** [comment]
넵. 기존 INTERESTING을 남겨두자고 하셔서... 
맘 같아서는 기존 INTERESTING을 바꾸고 싶지만 ㅋㅋㅋ 하위호환성을 위해...😂
